# Zen CLI Linting Configuration - v2 Format
version: "2"

linters:
  enable:
    # Core Go tooling
    - govet         # Built-in Go analysis
    - staticcheck   # Advanced static analysis
    - ineffassign   # Detect ineffective assignments
    - unused        # Find unused code

    # Code quality
    - gocritic      # Performance and style issues

    # Code style
    - nolintlint    # Proper nolint usage
    - unconvert     # Remove unnecessary conversions
    - misspell      # Fix common misspellings
    - whitespace    # Unnecessary whitespace

  disable:
    - errcheck      # Too many false positives
    - gosec         # Security issues (many false positives for CLI apps)
    - revive        # Fast golint replacement (mostly style preferences)

  # Linter-specific settings
  settings:
    misspell:
      locale: US

  # Exclusion rules
  exclusions:
    # Exclude some linters from test files
    rules:
      - path: _test\.go
        linters:
          - gosec
          - revive
          - gocritic

      # Exclude long lines with go:generate
      - linters:
          - revive
        source: "^//go:generate "

      # Exclude package comment requirements for CLI apps
      - linters:
          - revive
        text: "package-comments"

      # Exclude fmt print error checking for CLI output
      - linters:
          - errcheck
        source: "fmt\\.(Fprint|Print)"

      # Exclude defer close error checking for CLI apps
      - linters:
          - errcheck
        source: "defer.*\\.Close\\(\\)"

      # Exclude unused parameter warnings for CLI handlers
      - linters:
          - revive
        text: "unused-parameter"

      # Exclude exported comment requirements for constants
      - linters:
          - revive
        text: "exported.*should have comment"

      # Exclude var-naming for test packages
      - linters:
          - revive
        text: "var-naming.*meaningless package names"

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
  sort-order:
    - linter
    - severity
    - file

run:
  timeout: 5m
  modules-download-mode: readonly
