# Zen CLI Configuration Example
# This file shows all available configuration options with their default values

# Logging configuration
log_level: info  # trace, debug, info, warn, error, fatal, panic
log_format: text # text, json

# CLI settings
cli:
  # Disable colored output (can also be set via NO_COLOR env var)
  no_color: false

  # Enable verbose output
  verbose: false

  # Default output format for commands
  output_format: text # text, json, yaml

# Workspace settings
workspace:
  # Root directory for workspace operations
  root: .

  # Configuration file name to look for
  config_file: zen.yaml

# Development settings (optional)
development:
  # Enable debug mode (can also be set via ZEN_DEBUG=true env var)
  debug: false

  # Enable profiling
  profile: false

# Future configuration sections will be added here as features are implemented:

# AI agents configuration (planned)
# agents:
#   default_provider: openai
#   providers:
#     openai:
#       api_key: ${OPENAI_API_KEY}
#       model: gpt-4
#       max_tokens: 4096
#     anthropic:
#       api_key: ${ANTHROPIC_API_KEY}
#       model: claude-3-sonnet-20240229
#       max_tokens: 4096

# Integration settings (planned)
# integrations:
#   jira:
#     url: https://company.atlassian.net
#     username: ${JIRA_USERNAME}
#     api_token: ${JIRA_API_TOKEN}
#   confluence:
#     url: https://company.atlassian.net/wiki
#     username: ${CONFLUENCE_USERNAME}
#     api_token: ${CONFLUENCE_API_TOKEN}
#   git:
#     default_branch: main
#     auto_commit: true
#   slack:
#     webhook_url: ${SLACK_WEBHOOK_URL}
#     channel: "#development"

# Workflow templates (planned)
# workflows:
#   default_template: standard
#   templates:
#     standard:
#       stages:
#         - discover
#         - prioritize
#         - design
#         - architect
#         - plan
#         - build
#         - review
#         - test
#         - secure
#         - release
#         - verify
#         - feedback

# Quality gates (planned)
# quality:
#   gates:
#     code_coverage:
#       enabled: true
#       threshold: 80
#     security_scan:
#       enabled: true
#       fail_on_high: true
#     performance_test:
#       enabled: false
#       threshold_ms: 1000
