cli:
    no_color: false
    output_format: text
    verbose: true
log_level: debug
logging:
    format: text
    level: info
project:
    language: go
    metadata:
        git_provider: github
        go_module: github.com/daddia/zen
        go_version: "1.25"
    name: zen
    type: go
    version: "1.25"
version: "1.0"
workspace:
    created_at: 2025-09-13T23:24:35.430706+10:00
    name: zen
    root: .
    updated_at: 2025-09-13T23:24:35.430706+10:00
